# Generated by Django 4.2.7 on 2023-11-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='valid Python', max_length=255),
            preserve_default=False,
        ),
    ]
